### ISSUE TITLE
BT not working

### ISSUE THREAD

**Issue by snag1es** [richonguzman/LoRa_APRS_Tracker#109]
In the previous firmware, enabling Bluetooth in the configuration made it work after a reboot. Now, even when Bluetooth is enabled, it doesn't become active. When checking the configuration menu, Bluetooth is OFF. When switching it to ON, the situation remains the same: Bluetooth can't be activated. After reboot, Bluetooth switches back to OFF even if the configuration is preset to "active: true".

**Comment by richonguzman** [comment]
Hi

Two days ago I fixed this as someone mentioned it also

Please download it again and try

**Comment by PC9DB** [comment]
Hi,

This issue is still present.
At least on a Heltec Tracker.

Regards,
Mark

**Comment by richonguzman** [comment]
> Hi,
> 
> This issue is still present. At least on a Heltec Tracker.
> 
> Regards, Mark

HELTEC Wireless Tracker only has BLE not BT Classic

**Comment by PC9DB** [comment]
Thanks for your swift reply.

Does this mean I can't connect to my android device and use APRSdroid?

**Comment by richonguzman** [comment]
> Thanks for your swift reply.
> 
> Does this mean I can't connect to my android device and use APRSdroid?

I've been talking with APRSdroids developers and they confirmed that until a BLE Serial protocol is established they won't be able to support APRSDroid over BLE.

**Comment by PC9DB** [comment]
Too bad.
Any alternative to APRSdroid that does support connecting through BLE?

**Comment by richonguzman** [comment]
> Too bad. Any alternative to APRSdroid that does support connecting through BLE?

For now I only know Apple iOS apps over BLE... not  Android apps with BLE for APRS (as far as I know)

**Comment by PC9DB** [comment]
Okay, thank you very much for your help.

Best regards,
Mark
